### ISSUE TITLE
TypeError: Cannot read property 'indexOf' of undefined & TypeError: this._handle.close is not a function

### ISSUE THREAD

**Issue by vjancik** [mafintosh/why-is-node-running#13]
```
There are 7 known handle(s) keeping the process running and 5 unknown
Known handles:

/.../why-is-node-running/index.js:73
      return s.getFileName().indexOf(require('path').sep) > -1
                            ^

TypeError: Cannot read property 'indexOf' of undefined
    at /.../node_modules/why-is-node-running/index.js:73:29
    at Array.filter (native)
    at /.../node_modules/why-is-node-running/index.js:72:21
    at Array.forEach (native)
    at module.exports (/.../node_modules/why-is-node-running/index.js:69:9)
    at null._onTimeout (/.../index.js:18:5)
    at Timer.listOnTimeout (timers.js:92:15)

```

any idea what's causing this?

if I include `why-is-node-running` first in the file I get this error for change:

```
net.js:475
    this._handle.close(function() {
                 ^

TypeError: this._handle.close is not a function
    at TLSSocket.Socket._destroy (net.js:475:18)
    at connectErrorNT (net.js:997:8)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
```

Code:

``` javascript
const log = require('why-is-node-running')
const FirebaseServer = require('firebase-server')
const Firebase = require('firebase')

const instance = new FirebaseServer(5000, 'test.firebaseio.localhost', {
    states: {
        CA: 'California',
        AL: 'Alabama',
        KY: 'Kentucky'
    }
});
const client = new Firebase('ws://test.firebaseio.localhost:5000');
client.once('value', function(snap) {
    console.log('Got value: ', snap.val());
});

setTimeout(function() {
    log()
}, 1000)
```

On a Mac.

**Comment by mafintosh** [comment]
Think this is fixed in latest. If not please reopen :)
