### ISSUE TITLE
How to use it to troubleshoot Gulp tasks?

### ISSUE THREAD

**Issue by coaxial** [mafintosh/why-is-node-running#14]
I have a task that doesn't terminate and I'd like to use this package to find out what the problem is.

How do I do that?

When I call `log` at the end of my tasks sequence (with `runSequence`), I am getting this:

```
fs.js:1440
      if (!stat.isSymbolicLink()) {
                ^

TypeError: stat.isSymbolicLink is not a function
    at Object.realpathSync (fs.js:1440:17)
    at toRealPath (module.js:112:13)
    at tryFile (module.js:108:22)
    at tryPackage (module.js:96:10)
    at Function.Module._findPath (module.js:153:20)
    at Function.Module._resolveFilename (module.js:323:25)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.wrap [as FSInitialize] (/Users/coaxial/code/myproject/node_modules/why-is-node-running/index.js:21:22)
```

**Comment by yoshuawuyts** [comment]
what version of Node / npm are you running?

**Comment by Coaxial** [comment]
```
$ npm -v
3.8.8

$ node -v
v4.4.3
```

**Comment by mafintosh** [comment]
If you are able to use 8+ latest version will prob do the trick

**Comment by jonkoops** [comment]
Since the author has not gotten back to us I will assume this issue has been resolved. The version of Node.js used here is no longer supported anyways, so let's close this issue.

**Comment by coaxial** [comment]
Fair enough, it's been 8 years; I don't even remember what I was trying to accomplish :)
