### ISSUE TITLE
TypeError: Cannot read property 'indexOf' of null

### ISSUE THREAD

**Issue by errorx666** [mafintosh/why-is-node-running#21]
Node v7.7.2
why-is-node-running: npm 1.2.2

The error seems to happen [here](https://github.com/mafintosh/why-is-node-running/blob/master/index.js#L74).

```
There are 1 known handle(s) keeping the process running and 3 unknown
Known handles:


C:\Initech\node_modules\why-is-node-running\index.js:69
  known.forEach(function (obj, i) {
        ^
TypeError: Cannot read property 'indexOf' of null
    at C:\Initech\node_modules\why-is-node-running\index.js:73:29
    at Array.filter (native)
    at C:\Initech\node_modules\why-is-node-running\index.js:72:21
    at Array.forEach (native)
    at module.exports (C:\Initech\node_modules\why-is-node-running\index.js:69:9)
    at Timeout._onTimeout (C:/Initech/build/gulp/gulpfile.es:249:22)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)
```

**Comment by chrisl8** [comment]
Your fix works. Thank you!

**Comment by mafintosh** [comment]
should be fixed in latest
