### ISSUE TITLE
Error: Must give hashtype string as argument

### ISSUE THREAD

**Issue by julien-f** [mafintosh/why-is-node-running#4]
```js
require('why-is-node-running')
require('tls')
```

```
/tmp/node_modules/why-is-node-running/index.js:12
        var handle = new loaded[prop]()
                     ^

Error: Must give hashtype string as argument
    at Error (native)
    at new wrap (/tmp/node_modules/why-is-node-running/index.js:12:22)
    at new Hash (crypto.js:50:18)
    at Object.Hash (crypto.js:49:12)
    at getDefaultSessionIdContext (_tls_wrap.js:27:19)
    at _tls_wrap.js:17:33
    at NativeModule.compile (node.js:954:5)
    at NativeModule.require (node.js:902:18)
    at tls.js:221:21
    at NativeModule.compile (node.js:954:5)
```

**Comment by mafintosh** [comment]
fixed in 1.1.1
